// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqyvfwsmpqqiysteijkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxeXZmd3NtcHFxaXlzdGVpamt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjgwNzgsImV4cCI6MjA3MjgwNDA3OH0.Q-rVwdnjcBJzjjXnVL1Bn39gzIYQSNi7MlftKCFtK_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});